### ISSUE TITLE
Request: Add commitlint bot to check the commit messages

### ISSUE THREAD

**Issue by janisozaur** [nfrechette/acl#190]
The commit messages should adhere to a common standard, it makes them easy to browse especially when using `--oneline` log option.

See 
* https://www.git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines
* https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
* https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53
* https://chris.beams.io/posts/git-commit/
… and many more

The biggest issue right now is:
* Keep the subject lines short (you'll get various recommendations, usually between 50 and 70 chars)
* Keep the subject line separated with a single blank line

To keep the messages tidy, consider using a tool such as https://github.com/apps/commitlint/

**Comment by nfrechette** [comment]
Good idea, I'll check it out after the v1.2 release is done later this month.

**Comment by nfrechette** [comment]
A commitlint app was added. All new PRs should now execute it to ensure consistency.
I will also change how I work to always use PRs to merge as well to further ensure consistency.

**Comment by janisozaur** [comment]
Awesome, thanks!
