### ISSUE TITLE
python make.py -build on osx error => declaration of ‘c_str’ shadows a member of 'this'

### ISSUE THREAD

**Issue by matheboy** [nfrechette/acl#225]
The problem seems to be in string_view.h and string.h
Or maybe there is a compiler flag missing? documentation missing? I dont know but just following the documentation to get started throws this error. 
It should be fixed for good imho

**Comment by nfrechette** [comment]
Could you provide a bit more information? Which version of XCode are you using? Which compiler flags?

OS X builds with XCode 8/9/10 with CI with no issues and it typically warns for shadowed variables.

On Linux and OS X for GCC and Clang, CI compiles with `-Wall -Wextra -Wshadow -Werror`.

**Comment by matheboy** [comment]
hmm... wow! I just realized a small problem in my system. My conda setup with c++ compiler was detected instead of xcode. In that compiler the warnings were treated as errors. 
That explains why acl worked nicely integrated in our engine but kept failing for me when I tried to build it separated.
Apologies, I suppose the issue is solved now!
