### ISSUE TITLE
Allow game engines to define what a default sub-track should return/represent

### ISSUE THREAD

**Issue by nfrechette** [nfrechette/acl#354]
See this PR for original inspiration: https://github.com/nfrechette/acl/pull/348 by @ddeadguyy.

Animations are typically stored in one of two formats: relative to the identity transform or relative to some base pose.
I've already explored how to store relative to the bind pose [here](https://nfrechette.github.io/2018/05/08/anim_compression_additive_bind/).

As illustrated by that blog post, many joints end up being equal or close to the bind pose (the default character pose) which makes sense: not all joints are animated (and not all sub-tracks for joints that are animated).

ACL currently considers sub-tracks to be in one of 3 possible states: animated (with N samples), constant (with 1 sample), or default (equal to the identity, 0 sample).

In practice, animations that aren't relative to some base pose have their sub-tracks rarely equal to the identity. Instead it would be best if the default sub-track value could be something provided by the game engine: the bind pose. This would allow ACL to store sub-tracks that are equal to the bind pose with just two bits since we'll be able to avoid storing the bind pose per clip (it's often used for many things at runtime and could easily be provided by the game engine).

However, this is a lossy process and special care must be taken. If a clip is compressed with that assumption and the bind pose isn't provided during decompression, then sub-tracks returned by ACL that are default will not be able to return the right value. In a sense, either those sub-tracks must be skipped during decompression or the bind pose must be provided and looked up.

ACL 2.0 reworked the compression API and removed the `RigidSkeleton` which previous contained the `bind_transform` for debugging purposes. We would have to re-introduce the concept. Since this is optional, a separate `track_qvvf` should be provided to the compression API. Compression can continue normally except that when we detect if a track is default, we check against the bind pose if it is provided instead of the identity. The compressed clip will contain a new metadata flag to mark it as 'bind pose needed/aware'. During decompression, new optional functions on the pose writer will be added to handle this. Together with the metadata flag, we'll be able to assert at runtime that proper support is handled.

Decompression can be handled in one of two ways by the engine:
* Skip default tracks and output nothing
* Read the bind pose value and output it

The first case would be used when the engine pre-fills the output buffer with the bind pose. We would skip default sub-tracks to avoid overwriting the value.

The second case is more efficient.

To this end, a new function on the pose writer will be added: `handle_default_rotation(uint32_t track_index, rtm::quatf_arg0)` (and translation/scale). ACL will continue to provide the identity transform as an argument and it will be up to the game engine to handle default sub-tracks through the pose writer implementation.

This branch will be used for the development work: [feat/improve-bind-pose-handling](https://github.com/nfrechette/acl/tree/feat/improve-bind-pose-handling)

**Comment by ddeadguyy** [comment]
> ACL 2.0 reworked the compression API and removed the RigidSkeleton which previous contained the bind_transform for debugging purposes. We would have to re-introduce the concept. Since this is optional, a separate track_qvvf should be provided to the compression API. 

Should we consider adding the bind transform as a member of track_desc_transformf?  It already does some of the work that the old skeleton class used to do, such as tracking parent-child connections, and this would be similar.  Default values would be identity, to maintain default behavior.

**Comment by nfrechette** [comment]
Yes, that's a good idea I think. Let's call this new member the `default_value`. This will extend to scalar tracks as well down the road. For transforms, it'll be the `qvv_identity()` by default and a game engine can provide a unique value per bone (the bind transform).

During compression, we should detect if every track uses the same default value (e.g. identity). If it is the case, we need to add a new flag on the metadata of the compressed clip to say as such (one flag for rot/trans/scale).

During decompression, the `track_writer` provided should control this. A new function should be added that returns whether a single default value is used or not: `get_default_rotation_mode()` which returns an enum (`default_sub_track_mode`) that says `constant` (same for all sub-tracks of that type) or `variable` (different for every sub-track). This will allow us to query the default value once and keep it in a register for every sub-track when we can (like we do now). Game engines will be able to mix and match. It isn't unusual for the bind pose to have the default scale for example or to have the identity rotation and just have translation differ. Two new functions should be added on the writer to handle this: `get_default_rotation()` called when we are constant, and `get_default_rotation(uint32_t track_index)` called when we are variable. The default implementation of the writer can use constant mode and return the identity. The assembly generated should end up being the same it is now.

This extends naturally for translation/scale as well.

The only quirk is scale. Right now this depends on the additive/non-additive classification.

```c++
// Our default scale is 1.0 if we have no additive base or if we don't use 'additive1', otherwise it is 0.0
header->set_default_scale(!is_additive || additive_format != additive_clip_format8::additive1 ? 1 : 0);
```

We probably won't need this anymore since the writer will explicitly handle it. Sadly, this would mean that game engines will need to modify their custom track writer to handle this. If they don't and they had additive animations that relied on this behavior, a minor version update will cause a break. To keep the transition as smooth as possible, we could add a new enum to encapsulate the track writer version the game engine supports (and add a new function on the track writer that returns the version supported). The current default value would end up being version 0. Version 1 would be the new API we are introducing with this where scale is handled by the writer. We can query the version and fallback to the current behavior if game engines do not update their track writer to version 1. Once ACL 3.0 comes around, we can assert and fail if versions prior to 1 (or whatever future version) are used and force game engines to upgrade properly. Once this happens, we'll be able to remove the default scale property for good and reclaim that space but I would probably keep it around to rename it instead to something like `is_additive` to allow game engines to mimic the old behavior.

Together with this information, at runtime during decompression we can assert if a compressed tracks instance was compressed with constant/variable default values and ensure that the track writer provided matches as well (during the decompression context initialization).

How does that sound? Game engines that upgrade to ACL 2.1 and do not change the default value nor their track writer will continue to function as before. Those that do, can benefit from the new API for optimal codegen. Once ACL 3.0 comes, everything migrates to the new track writer API.

Is there a way we can mark the track writer version 0 as being deprecated somehow such that the compiler will warn? `static_assert` could work but that will be fatal. Ideally I'd like to have a deprecation warning until ACL 3.0 where we'll fatally assert at compile time. Maybe through a template specialization? I'll have to see what we can cook up.

**Comment by ddeadguyy** [comment]
Sounds reasonable.  I don't have uses cases for _additive1_, so I can poke at this in my fork of _feat/improve-bind-pose-handling_ up to that point.

**Comment by nfrechette** [comment]
I am starting the final review process to get this merged into develop.
I'll be doing the necessary version bump and validation.

**Comment by nfrechette** [comment]
I've got the code pretty much ready to go now. I'll run regression test one more time and I'll try it out in the UE4 plugin as well.
If everything looks good, I'll merge into develop soon.

**Comment by nfrechette** [comment]
I went ahead and merged the changes into develop.
I think I can come up with a way to integrate support for this in the UE4 plugin and I'll try it out in the next few weeks. Any further changes required will be made in new branches/PRs.

Thanks @ddeadguyy !
