### ISSUE TITLE
Allow frame stripping per clip

### ISSUE THREAD

**Issue by nfrechette** [nfrechette/acl#360]
Frame stripping is currently only implemented at the database level. But, we could also support it per clip very easily.
We should expose a new flag in the compression settings to optionally drop whole key frames up to some percentage.

We should always remove whole key frames that keep us below the current error threshold. These are safe to remove. However, doing so will increase the compression time perhaps considerably compared to what we have now. The current 'Medium' compression level should become 'Low' with 'Medium' and up now performing the safe key frame removal automatically.

**Comment by ddeadguyy** [comment]
> We should always remove whole key frames that keep us below the current error threshold.

If you're actively working on this part now, we're happy to wait for 2.1.  Otherwise, I can take a stab at it.  LMK.

**Comment by nfrechette** [comment]
I haven't begun working towards 2.1 yet so go ahead!

**Comment by nfrechette** [comment]
I will begin work on this shortly, stay tuned!
