### ISSUE TITLE
require bool curve support

### ISSUE THREAD

**Issue by 2226415223** [nfrechette/acl#467]
does it support bool mode, don't lerp between neighbor frame but only use left value.
it's very common to enable or disable some object in neighbor frame, unity translate 0 to False and (>0) to True
![image](https://github.com/nfrechette/acl/assets/62322001/a96ddb4e-6811-461e-8f04-6225c41bc993)

**Comment by nfrechette** [comment]
For scalar and transform tracks, you can use per track rounding and simply `floor` for your bool tracks. See [here](https://github.com/nfrechette/acl/blob/develop/docs/handling_per_track_rounding.md) for details. You will need the `develop` branch for this. Note that ACL is almost feature complete for the next 2.1 release and this will go out later this year.
