### ISSUE TITLE
Investigate fixed point arithmetic

### ISSUE THREAD

**Issue by nfrechette** [nfrechette/acl#49]
Range reduction sometimes causes accuracy loss. Investigate fixed point arithmetic to see if it can improve accuracy.

Perhaps a mix of fixed point/float32 arithmetic should be used for optimal results?
Also keep in mind performance implications for the decompression.

http://x86asm.net/articles/fixed-point-arithmetic-and-tricks/

https://en.wikipedia.org/wiki/Fixed-point_arithmetic

https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=0ahUKEwj2_fSo87LXAhVV5GMKHS9BCVgQFggrMAE&url=http%3A%2F%2Fwww-inst.eecs.berkeley.edu%2F~cs61c%2Fsp06%2Fhandout%2Ffixedpt.html&usg=AOvVaw30e1B92ekXbTzJeUDNfMgb

Use a rotation track from CMU for a segment, 16 rotations.
Compare with current float32 code path.
Compare with float64 code path.
Compare with fixed point code path (possibly various precision settings).

Exhaustive comparison for every possible bit rate?

https://software.intel.com/en-us/forums/intel-isa-extensions/topic/301988

http://codesuppository.blogspot.ca/2015/02/sse2neonh-porting-guide-and-header-file.html

**Comment by nfrechette** [comment]
Research investigation is done in this branch: https://github.com/nfrechette/acl/tree/research/float-vs-double-vs-fixed-point

**Comment by waykohler** [comment]
https://fgiesen.wordpress.com/2012/08/15/linear-interpolation-past-present-and-future/
Have a look under present, it might apply to you.
That future fma tech looks interesting :)

**Comment by nfrechette** [comment]
Ah yes I remember that article but couldn't find it a little while back. I'll create a separate issue to investigate this as I use the inaccurate lerp it seems. I seem to remember testing both and picking this one because it improved the results but I can't recall 100%. It's worth measuring and publishing the results for sure.

The FMA stuff is something I definitely want to do later on. Right now my desktop and console gpus support FMA just fine but console cpus do not. Mobile devices might also support it already. I have a task in my trello backlog for this but I haven't migrated everything here yet for the post-1.0 work.

Thanks for the link!

**Comment by waykohler** [comment]
The FMA was mentioned in the article from 2012 as future tech, just found it funny.

Yeah the Jaguar has its limits, crippled AVX and slow signed simd integer multiply bothers me once in a while.
Better than PowerPC though, load hit store was a nightmare.

**Comment by nfrechette** [comment]
Conclusion can be found here: http://nfrechette.github.io/2017/12/29/acl_research_arithmetic/
